# Generated by Django 6.1.1 on 2026-09-29 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('head', models.CharField(max_length=255, verbose_name='Завідувач кафедри')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст головної сторінки')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Опис')),
                ('coordinator_name', models.CharField(max_length=255, verbose_name="Ім'я координатора набору")),
                ('coordinator_contact', models.CharField(max_length=255, verbose_name='Контакт координатора набору')),
                ('disciplines', models.TextField(verbose_name='Список дисциплін')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='fsnst_app.department', verbose_name='Випускова кафедра')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('position', models.CharField(max_length=255, verbose_name='Посада')),
                ('degree', models.CharField(max_length=255, verbose_name='Ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='fsnst_app.department', verbose_name='Кафедра')),
            ],
        ),
    ]
