# Generated by Django 6.1.1 on 2026-09-29 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsnst_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to='fsnst_app.teacher', verbose_name='Завідувач кафедри'),
        ),
    ]
