# Generated by Django 6.1.1 on 2026-10-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsnst_app', '0005_populate_exchange_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='exchangeprogram',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва університету'),
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Університет (старе)'),
        ),
    ]
