# Generated by Django 6.1.1 on 2026-10-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsnst_app', '0007_split_university_and_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeprogram',
            name='university',
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(default='Не вказано', max_length=100, verbose_name='Країна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='university_name',
            field=models.CharField(default='Не вказано', max_length=255, verbose_name='Назва університету'),
            preserve_default=False,
        ),
    ]
